name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mveyone/docker-image-autobuild:latest
    - name: Push the Docker image
      run: docker login -u mveyone -p ${{ secrets.DOCKER_TOKEN }} && docker push mveyone/docker-image-autobuild:latest
